### PR TITLE
chore(docs): getCssValue takes param, returns RGB instead of hex

### PR DESCRIPTION
**Pull request by olore**
I am using v5.1.1, not sure what which point this changed

### CODE REVIEW

**Comment by Xotabu4** [comment]
Firefox returns HEX i think, Chrome rgba (i might be wrong). Haven't tested this in Edge/IE. 

I think it is better to just add message, that returning value depends on browser

**Comment by olore** [comment]
Thanks @Xotabu4, You are correct, I was testing in Chrome. I will try to confirm Firefox, but I don't think I can do Edge/IE.

[According to this](https://github.com/SeleniumHQ/selenium/blob/c181d392fb04c93f88be2549e2961a883221b6fb/java/client/src/org/openqa/selenium/htmlunit/HtmlUnitWebElement.java#L882
), it looks  like it **should** always return RGB.  This change was made in [June of 2015](https://github.com/SeleniumHQ/selenium/commit/c181d392fb04c93f88be2549e2961a883221b6fb#diff-f444f778bbe28cb2c8acc18f83265282R890)

**Comment by olore** [comment]
Fun fact - Chrome and Firefox both return RGB, at least for `background-color`, but it isn't the same:

```
  Firefox 50.0.2: rgb(247, 247, 247)
  Chrome 56.0:    rgba(247, 247, 247, 1)
```

**Comment by NickTomlin** [comment]
I'm in agreement with @Xotabu4 here; we should document this as differing between browsers but not actually change from Hex -> RGB. Perhaps just expanding the existing warning section to surface and document some of these issues?

**Comment by olore** [comment]
@NickTomlin that sounds fair. My main motivation for this was to update `getCssValue` function to show that it takes a param. The example was more of a collateral change. I like the idea of providing more detail. I'll make an update this week.

**Pull request closed without merging**
