### PR TITLE
updated deps

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Please update `selenium-webdriver` to `2.47.0` which has updated `ws` to `0.8.0` and release a new protractor version after that. This should fix https://github.com/angular/protractor/issues/2489 and the problems we see with npm3 and Node4.

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
I signed it!

**Comment by BarryThePenguin** [comment]
@donaldpipowitch are you aware of any workarounds while we wait for this to merge?

**Comment by donaldpipowitch** [comment]
Well, I use `"protractor": "donaldpipowitch/protractor#patch-1"` in my `package.json` until this is merged and a new version will be published. Works for me.

**Comment by BarryThePenguin** [comment]
Sounds good, I didn't think of that

**Comment by nizhu** [comment]
thanks @donaldpipowitch was just about to fork myself :)

**Comment by juliemr** [comment]
We need to make sure that the issue documented in #2245 has been fixed up before we can do a full update. Just to note that this will take some more investigation.

I realize that this is causing pain, and we'll be working to get some fix out very soon. Thanks for your patience!

**Comment by juliemr** [comment]
Done in 2.4.0. Thanks!

**Comment by donaldpipowitch** [comment]
Thank you!

**Pull request closed without merging**
