### PR TITLE
Add code examples for changes in  protractor 6.x

### LINKED ISSUE #5206: Documentation Update
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: 15.x``
- Protractor Version: 6.x``
- Angular Version: ``
- Browser(s): Chrome
- Operating System and Version Win 7, 10, Mac
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature

Please update the public facing documentation, particularly the tutorial and the examples. Due to recent upgrades, the protractor newbies and user community should be made aware: 

1. That the version selection process in webdriver-manager now points to the most recent version. It may not always be possible to synch with Chrome, so users should be advised how to specify a current and not a future version of the browser/driver. I do not know if this will affect other browser/drivers.

2. Due to the rise of async, Protractor 6.x and beyond require await/async. Newbies and people with long running scripts will not know this and will likely not look it up. Please change the tutorial and examples to reflect this.

- Is this a breaking change? (How will this affect existing functionality)

Yes, it will take users by surprise.

Cheers, RW
P.S. I'm out there trying to evangelize Protractor to the masses, so this will help considerably.

### PR DESCRIPTION
**Pull request by RoakyWood**
docs(*): Update home.html to reflect changes in webdriver-manager and protractor 6.0

Add explanation of how webdriver-manager now uses the most recent browser version and setting the particular version may be required.
Add alternative code sample to show how to update to a particular version of webdriver-manager
Add explanation of how async/await is now required for protractor 6.x and beyond and that users must acquaint themselves with such syntax
Add new code sample using async/await

Closes #5206

### CODE REVIEW

**Comment by RoakyWood** [comment]
I signed the CLA

**Comment by RoakyWood** [comment]
Unclear what Travis/CI is checking as this was a documentation update.

**Comment by cnishina** [comment]
Please read the googlebot. I think you need to have the exact wording. I'll re run the Travis tests.

**Comment by cnishina** [comment]
Ping, could you try the CLA again. Thanks!

**Comment by RoakyWood** [comment]
I signed it!

**Comment by cnishina** [comment]
I'm not sure what's going on here. I cannot check your status on this. You could check your account to ensure you have signed it. This usually is a pretty smooth process so I'm not sure what's going on.

**Comment by RoakyWood** [comment]
@cnishina I cannot find any contact method on the CLA site to resolve any issue. If you are aware of such, please advise.

**Comment by cnishina** [comment]
Did you visit https://cla.developers.google.com/ to sign it? When I navigate to the site, I can see that I have a "Google Individual CLA" under the individual agreements and the date signed. Also you should set your email for your git config with `git config --global user.email "email@example.com"` (https://help.github.com/en/articles/setting-your-commit-email-address-in-git) This should match the email you used in your CLA.

**Comment by cnishina** [comment]
Pinging again.

**Comment by RoakyWood** [comment]
I signed it!

**Comment by RoakyWood** [comment]
@cnishina I have taken all of those steps. 

It would be preferable if the CLA site: 
1. Allowed the user to delete a defective or erroneous CLA and/or 
2. Had some link or point of contact for help with a CLA issue.

It becomes opaque once you submit.

**Comment by RoakyWood** [comment]
@cnishina I see RoakyWood@users.noreply.github.com when I add .patch on the pull request. Do I need to make my email public for the CLA to take?

**Comment by RoakyWood** [comment]
Unable to resolve CLA issue. I assume that various updates will resolve this issue.

**Comment by cnishina** [comment]
Your email that you sign the CLA should match your git config email address. I did not use `@users.noreply.github.com` email address. I used my email address I use to log into github. I then set that email address in my git global config and used that same email address to sign the CLA. Maybe try again with that?

**Comment by RoakyWood** [comment]
@cnishina Thanks. I did try that. It’s nothing I can fix on my end.

RW

**Pull request closed without merging**
