### PR TITLE
chore(testapp): Use newer angular beta

### PR DESCRIPTION
**Pull request by sjelin**
Need this for #3024

### CODE REVIEW

**Comment by cnishina** [comment]
This looks fine except this definitely makes the flaky test #3000 fail 100% of the time. This could might need some attention.

**Comment by cnishina** [comment]
Should probably get #3127 merged in first to pass this test. Other than that, LGTM

**Comment by sjelin** [comment]
Blocked on https://github.com/angular/angular/issues/8089.  Assigning Julie since that bug is much more her domain.

**Comment by juliemr** [comment]
See https://github.com/angular/angular/issues/8219

We decided this is not blocked, since we should be running `setTimeout` outside of the Angular zone.

**Comment by sjelin** [comment]
`setInterval` is now being run outside of NgZone

**Comment by sjelin** [comment]
Craig assigning back to you since you're on call

**Pull request merged**
