### PR TITLE
Update chromedriver to 2.19 and iedriver to 2.47

### PR DESCRIPTION
**Pull request by Anufriev**
I updated chromedriver to 2.19 and iedriver to 2.47

https://github.com/angular/protractor/issues/2393

### CODE REVIEW

**Comment by Anufriev** [comment]
I signed!

**Comment by juliemr** [comment]
We need to make sure that the issue documented in https://github.com/angular/protractor/issues/2245 has been fixed up before we can do a full update. Just to note that this will take some more investigation.

**Comment by juliemr** [comment]
Done in cfd8d000c2aa1686c4a90164baf4e04976ee0587 (and with changes to our CI as well). Thanks for the PR!

**Comment by Anufriev** [comment]
Thanks!

**Pull request closed without merging**
