### PR TITLE
Issue #4202 - Add attributeContains and attributeIs to expectedConditions lib

### PR DESCRIPTION
**Pull request by marleitao**
Comments of elementToBeSelected method just changed because I executed 'npm run format'.

### CODE REVIEW

**Comment by marleitao** [comment]
I signed it!

**Comment by heathkit** [comment]
Thanks for including tests and detailed docs! Our CI was broken until recently - could you please rebase this and I'll take another look?

**Comment by wulfovitch** [comment]
I have also a use case for this feature (adding a attributeContains to ExpectedConditions library). Could someone review this pull request? Thanks! :)

**Comment by marleitao** [comment]
@heathkit @Marketionist not sure if you need to approve something, but basically I've merged your code and now apparently you need to approve your changes. Can you check what's missing? Without that my implementation cannot be merged.

**Comment by heathkit** [comment]
Can you rebase this against master so it's a single commit, with the message formatted as per the [developer guide](https://github.com/angular/protractor/blob/master/DEVELOPER.md). Thanks!

**Comment by heathkit** [comment]
Closing as requested.

**Pull request closed without merging**
