### PR TITLE
Update spec.ts

### PR DESCRIPTION
**Pull request by holdfenytolvaj**
fix import and text check

### CODE REVIEW

**Comment by holdfenytolvaj** [comment]
I signed it!

**Comment by holdfenytolvaj** [comment]
dfdfd

**Comment by holdfenytolvaj** [comment]
It seems the second await is only needed because of the last promise skip bug

**Comment by holdfenytolvaj** [comment]
Double checked, so with the current typescript 2.0.3, it is needed to have the second async
otherwise, the expect - check wont be done. (e.g. if in the next test you write
`await browser.get('google.com')`
it will throw an exception because the previous test hasn't been finished.) It seems this is only needed if there is at least one await call before the expect.

**Comment by mgiambalvo** [comment]
Thanks for the fix!

**Pull request merged**
