### PR TITLE
update selenium-webdriver

### PR DESCRIPTION
**Pull request by benitogf**

### CODE REVIEW

**Comment by NickTomlin** [comment]
We should be very careful when updating dependencies like Webdriver. In addition, you've commented out some linting related code without an explanation. 

Could you provide some reasoning behind these changes? If not, i'll go ahead and close this PR in 3 days. Thanks!

**Comment by benitogf** [comment]
Hello Nick, about the commented lines, both commands (npm install, tsc) produce no output so checking that to determine if there was an error is breaking this test on my side, please let me know if I'm missing something about it

**Comment by benitogf** [comment]
cla signed

**Comment by csvan** [comment]
Any news on this? What is needed to get it included? The older Selenium version in Protractor is a problem for running tests in Chrome Headless.

**Comment by timbru31** [comment]
Is this still relevant or can this (stale) PR closed? Because https://github.com/angular/protractor/commit/0fbc2c0ac12992bd61712188a96aef6684bef0c1 landed and bumped the version of selenium-webdriver.

**Comment by qiyigg** [comment]
Already updated to 3.6.0. Close the PR

**Pull request closed without merging**
