### PR TITLE
fix(debugger): expose require into debugger

### PR DESCRIPTION
**Pull request by hankduan**

### CODE REVIEW

**Comment by juliemr** [comment]
I like it!

**Comment by hankduan** [comment]
Is that a LGTM? =)

**Comment by SomeKittens** [comment]
Thanks to you both!

**Comment by juliemr** [comment]
Yes it is, I'm just slow!

**Comment by hankduan** [comment]
committed via https://github.com/angular/protractor/commit/ef0fbc096035bb01d136897ca463892ceca56b73

**Pull request closed without merging**
