### PR TITLE
fix(grep): change excluded tests to disabled instead of pending

### LINKED ISSUE #3952: Using --grep will call every defined beforeAll() in your suite/spec
When using `--grep` to delineate individual tests across a suite of multiple specs, each defined `beforeAll`() will be called, even those belonging to specs that do not contain a captured test. This is troublesome as it adds significant setup time to a test run that is unnecessary, and can lead to workflow corruption. 

Note that superfluous `beforeEach()`s are not called (just the appropriate ones). Also note that this is directly related to issues experienced by users on https://github.com/angular/protractor/issues/164, but that has been closed without response.

Ideally for each test that is captured via `--grep`, it will look upwards and run the corresponding `beforeAll()` and `beforeEach()`, run the captured test, then run `afterEach()` and `afterAll()`, then move to the next captured test and repeat. This will avoid running "extra" `beforeAll()`s.

I really love the `--grep` functionality and would love to see it better supported! The `iit/xit/fit` paradigm requires manually editing potentially hundreds of tests across a ton of files, which is tedious and does not fit well into fully automated CI. `--grep` (plus a suite of official tags) is my current approach and typically works very well, except for this one inconvenience. 

Example:
``` javascript

spec01.js:

describe('Spec 1.1', function() {

    beforeAll(function() {
        console.log('1.1 beforeAll executed');
    });

    beforeEach(function() {
        console.log('1.1 beforeEach executed');
    });

    it('Test case 1.1.1', function() {
        console.log('1.1.1 test case executed');
    });

    it('Test case 1.1.2', function() {
        console.log('1.1.2 test case executed');
        expect(1).toEqual(1);
    });
});

describe('Spec 1.2', function() {

    beforeAll(function() {
        console.log('1.2 beforeAll executed');
    });

    it('Test case 1.2.1', function() {
        console.log('1.2.1 test case executed');
    });
});

-------------------------------------------------
spec02.js:


describe('Spec 2.1', function() {

    beforeAll(function() {
        console.log('2.1 beforeAll executed');
    });

    beforeEach(function() {
        console.log('2.1 beforeEach executed');
    });

    it('Test case 2.1.1 #RunThisTestOnly', function() {
        console.log('2.1.1 test case executed');
    });
});

```

Let's assume these files are captured in the "all" suite, and then run with: `protractor conf.js --suite=all --grep="#RunThisTestOnly"`

Output:
```
Spec started
1.1 beforeAll executed

1.2 beforeAll executed
2.1 beforeAll executed
2.1 beforeEach executed
2.1.1 test case executed
```

The main problem here is this is adding x-minutes of superfluous setup time to my test run. Also, in theory, if your beforeAll()s were written correctly, you shouldn't have conflicts...but it is entirely possible, and will require some babysitting. 

Thank you and keep up the great work!

### PR DESCRIPTION
**Pull request by eileenzheng**
This is an attempt to fix #3952 .

In Jasmine, `beforeAll()` is executed for `pending` tests, but not `disabled` tests. This pr set all tests that are excluded from running to `disabled` so the corresponding `beforeAll()` won't run.

### CODE REVIEW

**Comment by eileenzheng** [comment]
Is there anything I can do to get this pr merged? @qiyigg

**Comment by qiyigg** [comment]
Hi, I have rebuilt the test, let's see that first. It seems the circleCI is not stable recently.
In general, I will take a look at the test first, if the test doesn't pass, I won't merge it.

**Comment by eileenzheng** [comment]
@qiyigg OK thank you. I was a bit confused about circleCI as it fails in master as well...The unstableness explains it.

**Comment by qiyigg** [comment]
It seems there's something wrong with the circle CI again.
I will take a look at the circle CI as well as this PR and ideally make a new release this week, sorry for the late response.

**Comment by marcdacz** [comment]
any updates on this issue? thanks heaps!

**Comment by qiyigg** [comment]
@eileenzheng 
To make the CircleCI run properly, you probably need to rebase your PR to the head. I found the PR was created before my CircleCI change was checked in.

One little concern is change filtered test to disabled will affect the result reporting. But it might be ok in this situation

Before:
151 specs, 0 failures, 104 pending specs
Finished in 15.257 seconds

After:
Ran 47 of 151 specs
47 specs, 0 failures
Finished in 14.705 seconds

**Comment by eileenzheng** [comment]
@qiyigg thanks! I just pushed the rebase commit and all checks passed.

**Comment by qiyigg** [comment]
thanks, merged.

**Comment by eileenzheng** [comment]
thank you!!

**Pull request merged**
