### PR TITLE
fix(test): fix long async spec

### LINKED ISSUE #3000: Test spec/ng2/async_spec.js occasionally fails
The test: "should wait for a series of periodic increments" has been failing occasionally on Travis and should be fixed. The test clicks the action button, waits, then clicks cancel.

The text for the value should be the same after 3 seconds. However, this is resulting in a timeout... or mismatch in values. Below is the failure for timing out.

```
[launcher] Running 1 instances of WebDriver
Started
....F
Failures:
1) async angular2 application long async spec should wait for a series of periodic increments
  Message:
    Failed: Wait timed out after 4388ms
  Stack:
    Error: Wait timed out after 4388ms
        at /home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2241:22
        at Promise.invokeCallback_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:364:9)
    From: Task: <anonymous wait>
        at ControlFlow.wait (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2229:17)
        at WebDriver.wait (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/webdriver.js:688:29)
        at [object Object].to.(anonymous function) [as wait] (/home/travis/build/angular/protractor/built/protractor.js:68:25)
```

### PR DESCRIPTION
**Pull request by cnishina**
closes #3000.

### CODE REVIEW

**Comment by sjelin** [comment]
Do we understand why Expected Conditions don't work here?

**Comment by cnishina** [comment]
No. This should probably be investigated instead of this "fix".

**Comment by juliemr** [comment]
I would prefer investigating to figure out what's wrong too - maybe we'll learn something :P

**Comment by sjelin** [comment]
Ugh, still investigating, but I think it's a bug in the testability API.

**Comment by sjelin** [comment]
Assigning this to Julie, since she's the one with the Testability/Zone knowledge to solve the underlying issue.

**Comment by sjelin** [comment]
Closing since we figured out we need to run the interval outside NgZone

**Pull request closed without merging**
