### PR TITLE
fix(typings): Update selenium typings and fix tsc errors

### PR DESCRIPTION
**Pull request by NickTomlin**
This is a first crack at solving the typing issues raised in https://github.com/angular/protractor/issues/4148. I picked up some of the low-hanging fruit in regards to typing fixes

**Disclaimer**: I'm still getting used to the TS ecosystem, so if I missed something obvious here please educate me 😄 

Also, on a side note, who would we feel about bumping TS to `2.1.x`? We are still on `2.x`; I know there's hesitancy about moving to `2.2` or `2.3` so we could also wait until those are more accepted in the angular/angular tooling community.

### CODE REVIEW

**Comment by seanmay** [comment]
I am on board with the jump to TS2.1, short of anything I might be missing in terms of the prior team's reluctance.

While my favourite 2.1 feature is Readonly, I feel like keyof, Partial and Pick would be helpful in keeping type information sound, in various corners of Protractor.

**Comment by seanmay** [comment]
The code looks good, but I want to hold off on the merge, momentarily, due to discussions that Vikram and I have had around a move forward strategy, regarding bug-fixes and features which will break typing, externally, versus those that won't.

The intent, I believe, is to move the breaking changes and the like (ES6 promises inclusive) to a major branch, and complete the minor changes in master. Once this is done, I'll be back here, but I think this code is good to go.

**Comment by NickTomlin** [comment]
Hmm, after some more digging this may not actually resolve the issue in #4148 so holding off on a merge is good. I still think updating the typings and removing some of the todos is good though. 

Restructuring releases sounds good; let me know what we settle on and if there's any way I can help.

**Comment by mgiambalvo** [comment]
FYI, Protractor has to use the same TypeScript version that Angular is on. We sort of unintentionally upgraded to 2.1 while Angular was still on 2.0 and created a mess, so we had to downgrade.

Upgrade TypeScript as often as you can, but don't get ahead of Angular!

**Comment by heathkit** [comment]
Sorry, I'm going to close this as it's pretty outdated and I have no idea what's going on. We do need to update our selenium typings, though. It's also important to remember that we need to be on the same version of typescript as Angular.

**Pull request closed without merging**
