### PR TITLE
(cucumber) process no-snippets param for cucumber framework

### PR DESCRIPTION
**Pull request by karthiktv006**

### CODE REVIEW

**Comment by karthiktv006** [comment]
I signed it!

**Comment by karthiktv006** [comment]
I signed again.

**Comment by sjelin** [comment]
The issue is that the email address of author of the commits is not the same as that of your github account.  If you could sign with whatever email the commits were authored with that would be ideal, but just confirming that you are, in fact, the author would be sufficient.

**Comment by sjelin** [comment]
Merged in at e18d499

**Pull request closed without merging**
