### PR TITLE
feat(element): add second() command for selecting the second element

### PR DESCRIPTION
**Pull request by Marketionist**
**feat(element): add second() command for selecting the second element**

### CODE REVIEW

**Comment by Marketionist** [comment]
Fixes https://github.com/angular/protractor/issues/3838

**Comment by Marketionist** [comment]
Circle CI failed with "Error: does not exist in logs: Cannot run in debug mode with multiCapabilities, count > 1, or sharding" in protractor/scripts/exitCodes.js:13 - which is not related to current PR

**Comment by Marketionist** [comment]
@sjelin @cnishina please review

**Comment by juliemr** [comment]
I think that this adds complexity without adding any real value. `.get(1)` is just as easy to understand - and where do we draw the line here? `third()`? `sixteenth()`? I think first and last have real value, I'd prefer to not add anything in between.

**Comment by Marketionist** [comment]
@juliemr as far as I've seen (including questions from users of stackoverflow), most often used cases are: `first()`, `second()` and `third()`. This three shortcuts looked like a reasonable addition that will give more readability for 90% of cases.

But, anyway, it's up to you to decide if it should become a part of protractor syntax.

**Pull request closed without merging**
