### PR TITLE
Export Locator

### PR DESCRIPTION
**Pull request by barrtender**
by.cssContainingText returns a ProtractorLocator, but Locator couldn't be imported in a TS file.

### CODE REVIEW

**Comment by wswebcreation** [comment]
@barrtender 

I'm seeing you are doing all kind of commits on this PR containing comments and not and no new functionality. Is there a reason for doing that?

**Comment by barrtender** [comment]
@wswebcreation

Yeah I couldn't figure out how to get the circleci to run again. It keeps timing out. Looking at a couple other pull requests it looks like it's timing out for them too. Is this standard, and if so is there a better way for me to rerun to try to get it to not time out?

Thanks,
Eric

**Comment by wswebcreation** [comment]
@vikerman and @cnishina 

Can you see what's happening on the CircleCI. I can't figure this out and I don't have rights to restart them

**Comment by wswebcreation** [comment]
@vikerman 

Tnx for merging, but what about a new release ;-)

**Pull request merged**
