### PR TITLE
Update deppendencies to latest stable releases

### PR DESCRIPTION
**Pull request by evilaliv3**
This pull request is to start a travis-ci run and test against dependencies updates.

Among the various outdated and unstable dependencies what would be probable valid is to update to jasmine 2.4.1

\cc @sjelin @juliemr

### CODE REVIEW

**Comment by evilaliv3** [comment]
I signed it! yeeeee!

**Comment by evilaliv3** [comment]
Here you are @sjelin @juliemr !

The pull is ready for integration :)

**Comment by sjelin** [comment]
@juliemr I'm giving you this because you're in a better place to analyze the cost/benefits of updating all these dependencies.

**Comment by juliemr** [comment]
Gotcha, I'll take a look this week.

**Comment by evilaliv3** [comment]
i've rebased the pull request cause jshint released the 2.9.1 that was included by me as 2.9.1-rc2.

@juliemr can you remember to tale a look at this? thanks

**Comment by juliemr** [comment]
Sorry for the slow response, it's been a holiday week. I'll really take a look this week.

**Comment by evilaliv3** [comment]
no worry @juliemr and thanks for your time!

**Comment by juliemr** [comment]
Ok, I've rebased and squashed and confirmed that `npm test` passes.

This is now merged as 5930d1444aef2f053c132eb437d07f9b000d7803. Thank you!

**Pull request closed without merging**
