### PR TITLE
chore(jasmine): Upgrade to jasmine 3.1.0

### LINKED ISSUE #4788: Upgrade to jasmine 3.1.0
Feature Request
---

Upgrade to jasmine 3.1.0

Jasmine 3 has been released for a while. A particular reason I want protractor to follow up is   jasmine/jasmine/#842 finally allow specDone support async.

### PR DESCRIPTION
**Pull request by awarecan**
Resolve #4788, #4708

Jamine 3 change the random default to true, however I want to keep protractor's default to false to avoid breaking changes.
done() accept error as parameter in Jasmine 3
beforeEach() no longer allow in it() in Jasmine 3

This is a rework for PR #4809

### CODE REVIEW

**Comment by qiyigg** [comment]
Please take a look at the commit format and change the commit message accordingly:
https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#commit-messages

This change makes sense to me, but updating major version of Jasmine involves with some [breaking changes](https://github.com/jasmine/jasmine/blob/master/release_notes/3.0.md), I'd like to wait for a while.

**Comment by simonua** [comment]
@qiyigg, is there sense releasing a `-beta` package, not tagging it with `latest`?

**Comment by qiyigg** [comment]
@simonua One problem is do we keep merging new PR to beta? who maintains the beta? Essentially I don't want to let this repo to be too complicated, as you can see, I am the only person who takes care of this stuff in my free time. It would be great if more active contributors like you guys could help me maintain Protractor together.

**Comment by simonua** [comment]
@qiyigg, I can understand that. On that note, thank you very much for your time and stewardship. I'm very surprised to hear you are the only active maintainer at this time. Scary, considering individuals and organizations rely on this package.

I don't mind being added as a collaborator, but I will readily admit that my in-depth knowledge of protractor is not where it may need to be to make decisions on its future or on PRs being merged.

**Comment by awarecan** [comment]
Commit message updated.

No need for beta package. I can use it and convince other developers to use it in our real world projects as long as the PR merged,  We can hold off publish npm release for a while, until more users tried the Jamine 3.

**Comment by awarecan** [comment]
@qiyigg that confirmed my guessing. Haven't seen commits from @juliemr or @sjelin for a while.

**Comment by simonua** [comment]
@awarecan, commit message: `chroe` -> `chore`

**Comment by awarecan** [comment]
Some of my understanding for the break changes

## Replace old "catch exceptions" logic with proper fail fast with error reporting
A new command line parameter -fail-fast=true provided, it also possible passed in `jasmineNodeOpts.failFase` in jasmine/jasmine-npm

## Detect an Error passed to done and add an expectation failure
The change like that need to be done if you use similar structure to test exception thrown in your test.
Regular positive test won't be affect.
image

## Unify status for xdescribe and xit
It more likely will effect jasmine-reporters

## Suite level errors all report the same way (on suiteDone)
It more likely will effect jasmine-reporters

## Refactor QueueRunner and remove references to functions that Jasmine is done with
Don't know protractor ever use this QueueRunner

## expect(null).toEqual(jasmine.any(Object)) no longer passes
That may affect particular usage

## Default to running tests in random order
I handled that in my PR is to keep protractor still running test sequential unless you set `jasmineNodeOpts.random = true`

## Additionally, Jasmine 3.0 drops support for older browsers and environments. Notably:
Not related with protractor

In general, I feel those changes are not so breaking, we can add a section to [docs/jasmine-upgrade.md](https://github.com/angular/protractor/blob/master/docs/jasmine-upgrade.md) for better guide users

**Comment by asvishnyakov** [comment]
@awarecan Any update on this?

**Comment by Maximaximum** [comment]
Are there any updates on this very important PR? :)

**Comment by jscharett** [comment]
Can this PR be merged to add support for jasmine 3.x in protractor 5.x?

**Comment by awarecan** [comment]
Protractor 6 already included jasmine 3.3, therefore I would like to close this PR.

@jscharett I don't think they will maintenance 5.x branch, fell free to take my code to change your local protractor package.

**Pull request closed without merging**
