### PR TITLE
Change defer-bootstrap logic

### PR DESCRIPTION
**Pull request by hankduan**
*Bootstrap is done immediately when you call (add/remove/clear)MockModule
*Angular will deal with subsequent bootstrap without pausing for
   protractor (and bootstrap)
*browser.get (and other navigation) will be a straight call to wd
*back/forward will start working for protractor (with injected module)
*if another site redirects to Angular (e.g. login), mock modules can now be
   injected

Note: testapp/lib/angular_v1.2.9/angular.js is included for reference
      and will not be submitted as part of this PR (there will be a PR
      for angular)

Breaking changes:
*(add/remove/clear)MockModule will take an addition param (url), which
   is the url you are modifying the mock modules for. Injection will
   be done immediately.
*browser.get or any action will timeout if you have a $timeout > 10s
   in the app. ($timeout with waitForAngular was not supported before,
   just that now even page will not load subsequently)

Compatibility:
*bootstrap will not work for subsequent get/navigate if your browser
   does not support localSession
*bootstrap will not work for subsequent get/navigate if you are
   testing an older version of Angular

[Review on Reviewable](https://reviewable.io/reviews/angular/protractor/1155)

### CODE REVIEW

**Comment by juliemr** [comment]
After discussions today: - let's rebase this and actually take a look at it! We think it will be backwards compatible so shouldn't introduce problems. Also need to check browser compatibility for localstorage stuff.

**Comment by americoneto1** [comment]
@juliemr I need to use addMockModule with manual bootstrap (requirejs) for my E2E tests. Do you know if there is any workaround to resolve this issue?

**Comment by sjelin** [comment]
@juliemr I assume Hank is no longer working on this?

**Comment by sjelin** [comment]
@juliemr @mgiambalvo @cnishina Ping

**Comment by sjelin** [comment]
@juliemr ping ¿hola como estas? this issue hasn't gone away I still keep getting questions about it

**Comment by juliemr** [comment]
We're going to add this to our things to address in Q2.

**Comment by juliemr** [comment]
I think this is out of date enough to just close - we want to look at these issues, but leaving this PR open ain't helping.

**Pull request closed without merging**
