### PR TITLE
chore(test): re-work interactive_tests to native Promise

### PR DESCRIPTION
**Pull request by CrispusDH**
- re-work interactive_tests to native Promise. Locally tests were passed. But I'm not sure how to run tests in a proper way because `test.run()` returns Promise that I does not resolve.
- fix `ng2_async_spec`: change waiting value from `1` to `2`

@cnishina , @heathkit  could you take a look at this PR, please

### CODE REVIEW

**Comment by CrispusDH** [comment]
Reference #4995

**Comment by CrispusDH** [comment]
I don't know why but I can not get an error. The tests are passed locally. I mean `interactive_tests`. Probably it's broken somewhere inside.

**Comment by cnishina** [comment]
Is it because the thrown error is caught in the .catch? Maybe something like this?

`test.run().then(() => {}).catch(err => {console.log(err)}`

**Comment by CrispusDH** [comment]
I will try tomorrow, thanks.

**Comment by CrispusDH** [comment]
Move PR to https://github.com/angular/protractor/pull/5037

**Pull request closed without merging**
