### PR TITLE
fix(website): Site improvement - Locator by.name('field_name')

### PR DESCRIPTION
**Pull request by anibalsanchez**
A tweak to the documentation to add the Locator by.name.

Amazing tool!
Anibal

### CODE REVIEW

**Comment by anibalsanchez** [comment]
I signed it!

**Comment by qiyigg** [comment]
@anibalsanchez  Would you mind updating the comment according to https://github.com/angular/protractor/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by anibalsanchez** [comment]
This is an improvement to the site documentation. Not a change to protractor itself.

**Comment by qiyigg** [comment]
@anibalsanchez  you can just use fix(doc) or fix(website)

**Comment by anibalsanchez** [comment]
Done. I've just renamed the topic.

**Comment by qiyigg** [comment]
merged. thanks!

**Pull request merged**
