### PR TITLE
test(WIP): show issue with webdriver 2.46

### PR DESCRIPTION
**Pull request by juliemr**
[Review on Reviewable](https://reviewable.io/reviews/angular/protractor/2263)

### CODE REVIEW

**Comment by juliemr** [comment]
This just hangs. Passes with `selenium-webdriver@2.45.1`

**Comment by juliemr** [comment]
Possibly related to https://github.com/SeleniumHQ/selenium/issues/677

**Comment by hankduan** [comment]
Here's a reduced pure-webdriver example that demonstrates this:

```javascript
var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder().
  usingServer('http://localhost:4444/wd/hub').
  withCapabilities(webdriver.Capabilities.chrome()).
  build();

var flow = webdriver.promise.controlFlow();
var locator = webdriver.By.css('.hello-code');

flow.execute(function() {
  driver.get('http://www.angularjs.org');
});

flow.execute(function() {
  var helloCodeText = driver.findElements(locator).then(function(webElements) {
    return webElements[0].getText();
  })

  flow.execute(function() {
    return helloCodeText.then(function() {
      console.log("SUCCESS");
    });
  });

  driver.findElement(locator).getText();

  webdriver.promise.fulfilled().then(function() {
    return driver.findElements(locator);
  }).then(function(webElements) {
    return webElements[0].getText();
  });
});

driver.quit();
```

**Comment by juliemr** [comment]
Reported reduced case here: SeleniumHQ/selenium#715

**Comment by juliemr** [comment]
Note that this fails on both selenium-webdriver 2.45 and 2.46 if the locator is replaced with a native one, such as `by.css` (instead of `by.binding`)

See also https://github.com/SeleniumHQ/selenium/issues/363

**Pull request closed without merging**
