### PR TITLE
chore(plugins) refactor logging and feat(accessibility plugin)

### PR DESCRIPTION
**Pull request by juliemr**
Two improvements to make logging from the chrome a11y dev tools better.

### CODE REVIEW

**Comment by juliemr** [comment]
@marcysutton could you take a look at this one?

**Comment by juliemr** [comment]
@sjelin it would be great if you could also take a look at the changes to plugins here.

**Comment by marcysutton** [comment]
@juliemr looks fine to me, I'll work on handling warnings from the Chrome Dev Tools to go along with this. Look for it in a separate PR.

**Comment by juliemr** [comment]
thanks! Merged.

**Comment by sjelin** [comment]
I guess I missed the boat but it does LGTM :P

**Pull request closed without merging**
