### PR TITLE
docs(page-objects.md): Refactor the existing Page Object example

### PR DESCRIPTION
**Pull request by timothystone**
As presented, simply following the example will not run. This presents the Page Object example as a runnable set of spec + Page Object. See #4570

Open possibilities for future work include: carry the initial introduction over into a Page Object. Introduce `world`, etc.

### CODE REVIEW

**Comment by timothystone** [comment]
I signed it

**Comment by timothystone** [comment]
How do you restart a build? looks like a timeout. Are there "tests" needed for this content?

**Comment by timothystone** [comment]
The `travis` error looks false, a process timeout. Can someone evaluate?

**Comment by qiyigg** [comment]
tests have been rerun and passed.

**Pull request merged**
