### PR TITLE
Add Sauce Labs Mobile Testing(Test Object) and Kobiton capabilities to driver providers

### PR DESCRIPTION
**Pull request by lt-bstevens**
Sauce Labs and Kobtion customers are looking to test against the Real Device Cloud available through Test Object and Kobtion. These changes add that ability and will pull those credentials in to be used for remote connection, if credentials are present.
*Added testObject and kobtion as driver providers
*Changed configuration files to retrieve testObject data, if present. If not and kobiton data is present, kobiton will be used.

### CODE REVIEW

**Comment by lt-bstevens** [comment]
Test Object was acquired by Sauce Labs and is what Sauce Labs now uses for their Real Device Testing. These changes allow a user to interact with Test Object devices.

**Comment by lt-bstevens** [comment]
@wswebcreation , this PR is very similar to PR #4488 but it's for adding Test Object (SauceLabs Mobile).

**Comment by wswebcreation** [comment]
@qiyigg 

Can you please take a look at this one, it makes live easier for people who want to use the Mobile part of Sauce Labs

**Comment by qiyigg** [comment]
@wswebcreation 
OK, but I personally don't have any knowledge about test object, just take a look at some general issues. 

@lt-bstevens 
Hi, could you please check the doc below and update the commit message
https://github.com/angular/protractor/blob/master/CONTRIBUTING.md
Btw, the code itself looks good to me.

**Comment by wswebcreation** [comment]
@qiyigg

Ok, tnx, maybe @cnishina can also take a look at it

**Comment by lt-bstevens** [comment]
@qiyigg @wswebcreation  @cnishina , I've added a new commit that follows the standard from the Contributing markdown file. It's in commit 3b2646c.

**Comment by lt-bstevens** [comment]
I see that @qiyigg approved this already, are we waiting on @cnishina to approve as well before merging?

**Comment by wswebcreation** [comment]
Hi @lt-bstevens 

I'm not allowed to merge because I can't create a new version and push to NPM. This needs to be done by the core-team members. @qiyigg and @cnishina can do that.

@cnishina is I think the best person to judge the code and give the final approval on it. As far as I can see I don't see any problems.

**Comment by qiyigg** [comment]
@lt-bstevens @wswebcreation We can wait another week to get more review for this PR. If no other change is needed after this week, I can merge it directly. make sense?

**Comment by wswebcreation** [comment]
@lt-bstevens and @qiyigg 

I've talked to Craig and he'll check it this weekend, I'll try to remember him ;-)

**Comment by qiyigg** [comment]
OK, thanks!

**Comment by lt-bstevens** [comment]
I've added Kobiton as another driver provider as I've been working with their mobile automation offering as well. I've updated the commit message to reflect the addition, as well as the PR. The only difference between the files is variable names and the selenium address is a little different for Kobiton.

**Comment by lt-bstevens** [comment]
@wswebcreation @qiyigg ,

Just checking on the status of this. It doesn't look like @cnishina was able to take a look at it last weekend.

Thanks!

**Comment by wswebcreation** [comment]
@lt-bstevens 

True, I also forgot, sorry, will ping him again

**Comment by lt-bstevens** [comment]
Thanks @wswebcreation !

**Comment by lt-bstevens** [comment]
Happy New Year @wswebcreation @qiyigg and @cnishina ! It looks like this hasn't been reviewed yet by Craig. Any chance you can remind him again now that the holiday season is over? Thanks!

**Comment by lt-bstevens** [comment]
@wswebcreation just checking in on this one again. Any chance you could reach out again? Thanks!

**Comment by qiyigg** [comment]
I don't mind merging this PR if @cnishina doesn't have time to review it. It looks not harmful.
@lt-bstevens Also, would you mind keeping working on this if it does bring some bugs in the future.

**Comment by lt-bstevens** [comment]
@qiyigg that would be great. I'm fine with continuing to work on it if bugs do pop up in the future. They'd likely impact my work anyways so I'd be working on them anyways. Thanks!

**Comment by qiyigg** [comment]
@wswebcreation @lt-bstevens 
It seems @cnishina doesn't have time to review it. I just merge it directly.
Thanks!

**Comment by wswebcreation** [comment]
@qiyigg, that's fine with me. When will you make a new release?

**Comment by wswebcreation** [comment]
@qiyigg Ok

But then I would advise to only merge before a release instead of merge during a month. Otherwise people who try to debug on a git source that has not been released (except for doc changes), or am I seeing this wrong/you have different thoughts about it?

**Comment by qiyigg** [comment]
@wswebcreation 
My understanding is merging new PR to master won't affect releasing version. People who want to stick to stable version, they can just use release version (e.g. we have 5.2.2 tag right now), and users who want to access to the newest code, they can use master branch. There are some new changes in master that are not released, but they are kind of expected, aren't they?

**Comment by lt-bstevens** [comment]
@qiyigg @wswebcreation we use npm and a package file to get protractor into our project. So we won't have access to the changes made until the next release? Just trying to determine when we can access the code change. Thanks!

**Comment by qiyigg** [comment]
yes, this change only exists in master branch right now and you do need a new release to have all the new changes. 
The original plan is to release a new version at the end of month, but it is negotiable

**Comment by lt-bstevens** [comment]
If the release can be pushed up at all it would be greatly appreciated. We're currently unable to test mobile automation with automated builds via bamboo and have been delayed in our mobile efforts due to the project not having these changes. We'd hoped the changes would have been ready before the end of the year and are expected to show our findings and pick a mobile automation tool by the end of the month. If you can move the release up sooner it would be extremely helpful for us to hit our deadlines.

**Comment by qiyigg** [comment]
@lt-bstevens  I don't think I can do it this week, but I could try to make it next week, is that fine for you?

**Comment by lt-bstevens** [comment]
@qiyigg I completely understand if you can't do this week. Next week would be awesome! Thank you!

**Comment by wswebcreation** [comment]
@qiyigg 

You are right, it won't affect it. On the other hand, this remark of @lt-bstevens 

> we use npm and a package file to get protractor into our project. So we won't have access to the changes made until the next release

was my main reason. I think 95% (or even more) uses the NPM version, so waiting between 3-6 weeks on PR's / bugs being released to a new version on NPM is in my opinion, and from a user perspective, a bit to long. A lot of people rely on Protractor for their build and testprocess so this will affect them in the speed to release their products (or create hacks to test specific situations).

I'm not trying to give you more work, because I think you are doing a lot already,  but I'm also trying to approach it from a user perspective. With around 50.000-70.000 downloads a day I think I can speak for a lot of users ;-)

Grtz

Wim

**Comment by lt-bstevens** [comment]
@qiyigg @wswebcreation checking in on the status of the new release. When we last spoke you thought this week was a possibility, is that still the case? If so, do you know when you'd be doing that?

Thanks!

**Comment by qiyigg** [comment]
I will do it within this week. I plan to start it today, ideally I can make the release tomorrow.

**Comment by lt-bstevens** [comment]
@qiyigg awesome! Thank you!

**Comment by lt-bstevens** [comment]
@qiyigg any update on when the release will be? Thanks!

**Comment by qiyigg** [comment]
@lt-bstevens I tried to make a release last week but found the integration test in circleCI was broken. I looked into it for a while and then switched to other jobs. I will have some time to investigate it today, hopefully it can be fixed today and I can make the release.

**Comment by lt-bstevens** [comment]
Thanks for the update @qiyigg !

**Pull request merged**
