### PR TITLE
chore(docs): document more of selenium's functions on our website

### PR DESCRIPTION
**Pull request by sjelin**

### CODE REVIEW

**Comment by sjelin** [comment]
Michael I'm assigning this to you because I haven't assigned much to you in the past and I want to balance that out.

**Comment by manoj9788** [comment]
can't we just link in someway to the original docs ? in that it will reduce the rework if incase something actually changes and we loose track to change it here ? Thoughts ?

**Comment by sjelin** [comment]
We used to do that, but we decided to rewrite them because those docs don't use protractor-style code examples (e.g. `browser.findElement(webdriver.By.id("id"))` vs `element(by.id("id"))`)

**Comment by mgiambalvo** [comment]
Sorry I missed this!

**Pull request merged**
