### PR TITLE
docs(webelement): Remove takeScreenshot from docs.

### PR DESCRIPTION
**Pull request by mgiambalvo**
We don't seem to wrap this for WebElements.

### CODE REVIEW

**Comment by mgiambalvo** [comment]
Note that this is the takeScreenshot() method on WebElement, not the one on browser.

**Comment by juliemr** [comment]
Should we instead wrap this? It seems reasonable to add it to the `WEB_ELEMENT_FUNCTIONS` and document it.

**Comment by mgiambalvo** [comment]
I assumed it wasn't wrapped for a reason. But if you can't think of any reason not to wrap it, then we might as well go that way.

**Comment by juliemr** [comment]
It's new, so we just haven't gotten around to it. (https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v2482)

**Comment by mgiambalvo** [comment]
Ah, I see. As near as I can tell, this isn't supported yet in Chromedriver (even in 2.21)

**Comment by juliemr** [comment]
Hmm, let's wrap it anyway - if the error message is reasonable. (The command is `/session/:sessionId/element/:id/screenshot`: https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/javascript/webdriver/http/http.js#L275)

**Comment by sjelin** [comment]
Closing this since instead we're deciding to wrap it

**Pull request closed without merging**
