### PR TITLE
chore(tests): test for ngUpgrade support

### PR DESCRIPTION
**Pull request by sjelin**
`upgrade.js` taken from https://github.com/angular/angular/pull/7603

### CODE REVIEW

**Comment by sjelin** [comment]
Self: use actual upgrade.js

**Comment by sjelin** [comment]
Blocked on https://github.com/angular/protractor/pull/3121, which in turn is blocked on angular/angular#8089, which is probably best handled by Julie.

**Comment by sjelin** [comment]
Unblocked.  LMK what you think @juliemr

**Comment by juliemr** [comment]
LGTM.

**Pull request merged**
