### PR TITLE
Update withLoginConf.js

### PR DESCRIPTION
**Pull request by skalb**
Added missing return statement to work with 2.0

### CODE REVIEW

**Comment by glepretre** [comment]
:+1: There are no other references / docs where it should be added?

**Comment by juliemr** [comment]
This looks good - could you take a look at the CLA so we can merge?

**Comment by skalb** [comment]
@googlebot signed

**Comment by juliemr** [comment]
Thanks! Merged with a2cccb8b71603a1b75601c877960d0222aba548c

**Pull request closed without merging**
