### PR TITLE
chore(testapp): section off angular 1 testapp

### PR DESCRIPTION
**Pull request by sjelin**
Doing this in a separate commit/pull request because it was very non-trivial

### CODE REVIEW

**Comment by juliemr** [comment]
Can't we change the config `baseUrl` instead of changing this everywhere? Say change `spec/environment.js` so that it exposes:

```js
ng1BaseUrl:   baseUrl:
    'http://' + (process.env.HTTP_HOST || 'localhost') +
          ':' + (process.env.HTTP_PORT || webServerDefaultPort) + '/ng1/'
```
?

**Comment by sjelin** [comment]
Ok, updated

**Comment by juliemr** [comment]
Changes look good. Can you verify that it passes `npm test` as well as passing Travis? Then go ahead and merge.

**Comment by sjelin** [comment]
Did verify - that's how I found the other error! :stuck_out_tongue:

**Pull request merged**
