### PR TITLE
Add ng-apimock plugin to Community Plugins

### PR DESCRIPTION
**Pull request by mdasberg**
- Adds [ng-apimock](https://github.com/mdasberg/ng-apimock) to the list Community Plugins

### CODE REVIEW

**Comment by jlin412** [comment]
Does this mock plugin confine with angular 1?  I was told that angular-mock
won't with angular 2 yet.

**Comment by mdasberg** [comment]
It works with both angular 1 and 2.

Ng-apimock uses connect middleware to hook into your webserver.
When an expression matches, it will return the selected response for you.

From your protractor test you can select scenario's for your endpoints.
But in order to run concurrent test ng-apimock has to know which protractor instance is running.

So if you have 2 tests that both want a different response:
test 1: return status 200
test 2: return status 404

You don't want test 2 to get the selected response from test 1 and vice versa.

Ng-apimock uses for:
- angular 1 applications protractor.addMockModule and adds a header for each api call to identify
- angular 2 applications it uses a cookie to identify

**Comment by wswebcreation** [comment]
@heathkit 

Is there a possibility that we can merge this PR. @mdasberg is my colleague and I also work on ng-Apimock, so hopefully you can approve this.

**Comment by heathkit** [comment]
Weird, surprised I didn't see this back in February. It's cool to see so many plugins! Please rebase and fix conflicts, and I'll try to get it in soon.

**Comment by wswebcreation** [comment]
The conflicts are fixed, only the label is changed. Or am I missing something now?

**Comment by heathkit** [comment]
The merge commit https://github.com/angular/protractor/pull/4069/commits/01c4dc32f3cb05c1613888861494810cb56a12f5 is creating a conflict. 

You'll need to use `git rebase -i` to rebase the first two commits on top of master. This would also be a good time to collapse those two commits into one and give it a message that meets the [style guide](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#commit-messages). 

We do this so that it's easy to generate the changelog in a new release by looking at the commit history in master. That's why we avoid merge commits and rebase PRs to a single commit - to keep the commit history in master clean and readable.

**Comment by wswebcreation** [comment]
@mdasberg 

Can you rebase and update this PR. @heathkit will then merge it

**Comment by mdasberg** [comment]
@heathkit I rebased with master and squashed and rewrote according to the styleguide

**Pull request merged**
