### PR TITLE
node 0.11 ...

### PR DESCRIPTION
**Pull request by cybernet**
run test with node 0.11 :)

### CODE REVIEW

**Comment by juliemr** [comment]
See also https://github.com/angular/protractor/issues/1053

**Comment by juliemr** [comment]
We should start adding some smoke tests against node .11 but I don't think to re-run our entire suite to catch errors (this will create more travis traffic for all Angular builds). Let's only test against a small suite.

@cybernet would you like to update this PR to do that?

**Comment by sjelin** [comment]
@juliemr Tomorrow if you want to explain to me how to do this, I'll handle it

**Comment by sjelin** [comment]
Continued over at https://github.com/angular/protractor/pull/1783

**Pull request closed without merging**
