### PR TITLE
chore(deps): upgrade all to latest stable

### PR DESCRIPTION
**Pull request by AviVahl**
- fixed a few untyped places.
- cleaned up several imports/re-exports
- fixed `testapp`'s compatibility with node 12.
- adjusted saucelabs integration to new (typed) major. remove not-accepted "sauce agent".
- adjusted travis to run on node 8 (min supported) and 12 (current lts).
- removed custom sauce connect script. needs to be replaced with Travis's `sauce_connect` addon.

closes #5338

**master**:

`npm i` @ repo root:
`added 726 packages from 902 contributors and audited 8522 packages
found 116 vulnerabilities (1 moderate, 115 high)`

`npm i` @ `testapp` folder:
`added 377 packages from 241 contributors and audited 787 packages
found 65 vulnerabilities (30 low, 12 moderate, 23 high)`

**PR**:

`npm i` @ repo root:
`added 711 packages from 982 contributors and audited 7829 packages
found 0 vulnerabilities`

`npm i` @ `testapp` folder:
`added 362 packages from 331 contributors and audited 3658 packages
found 0 vulnerabilities`

### CODE REVIEW

**Comment by AviVahl** [comment]
Not sure what's up with the Travis Sauce Labs configuration. It fails on master as well. Tried various tweaks, but nothing worked.

CircleCI is passing, and so is a local run with `selenium-standalone`.

**Comment by AviVahl** [comment]
hey @heathkit, any chance you could review this.
I know many people are looking forward for a patch release compatible with TypeScript 3.7. This might help a bit.

**Comment by AviVahl** [comment]
closing due to lack of response. :(

**Comment by heathkit** [comment]
Sorry I missed this 😔 If you're up for it, if you could make this PR against the release-5.4 branch I'll make sure it lands. For the time being, we're only allowing non-breaking changes to the release-5.4 branch so that we can make patch releases.

**Comment by AviVahl** [comment]
Appreciate the response, even if a bit late.
I probably won't get to re-do these changes for the branch... busy with lots of other stuff these days.
Just letting you know, in case you want to take whatever from this PR's diff...

**Pull request closed without merging**
