### PR TITLE
chore(jasmine2): upgrade jasmine to 2.2

### PR DESCRIPTION
**Pull request by hankduan**
This will enable spec-based timeout (i.e. it('description', test_func, timeout))
and proper stack trace propagation

### CODE REVIEW

**Comment by juliemr** [comment]
Looks like tests are failing because the fix that I submitted for matching arrays from different contexts is not yet in jasmine. Can we wait for that?

**Comment by hankduan** [comment]
Doesn't seem like we have a choice :P

**Comment by hankduan** [comment]
I'm going to close this for now then since it's going to be a while before they release a new version

**Comment by juliemr** [comment]
Reopening so it's more searchable and I can remember what's going on :P

**Comment by juliemr** [comment]
Waiting for a release with https://github.com/jasmine/jasmine/pull/767

**Comment by JonDuffy** [comment]
Hi, 
Using jasmine 2.1.1 is giving me incorrect stack traces:
https://github.com/angular/protractor/issues/2094

Issue is resolved by upgrading to 2.2.1

**Comment by juliemr** [comment]
Update! Jasmine 2.3.0 is out. Protractor will test and update soon.

**Pull request closed without merging**
