### PR TITLE
chore(test): move ng2/timeout_spec off of the control flow

### PR DESCRIPTION
**Pull request by CrispusDH**
I'm not sure should I or not change expected error message (test is failed with the same result on CircleCI and locally)?
Expected error message: `Timed out waiting for asynchronous Angular tasks to finish`
Current error message: `Failed: script timeout: result was not received in 11 seconds` 

@cnishina , could you take a look at this PR, please

### CODE REVIEW

**Comment by CrispusDH** [comment]
Reference #4995

**Comment by cnishina** [comment]
Okay I looked into this a bit more, the failure is there probably because of this controlFlow call.

https://github.com/angular/protractor/blob/master/lib/browser.ts#L660 Probably the error is not properly thrown because we are do not execute the controlFlow(). We will come back to this when we untangle Protractor and the control flow.

**Comment by cnishina** [comment]
@CrispusDH Could you rebase this? I fixed the control flow issue in the browser. Thank you!

**Comment by CrispusDH** [comment]
@cnishina , unfortunately the error still the same as was

**Comment by cnishina** [comment]
Closing this one. It looks like we got it done.

**Pull request closed without merging**
