### PR TITLE
chore(testapp): run testapp on angular v1.5.0

### PR DESCRIPTION
**Pull request by juliemr**
See #2970

### CODE REVIEW

**Comment by juliemr** [comment]
@sjelin sanity check please?

**Comment by sjelin** [comment]
It looks fine to me.  Does website generation still work?

**Comment by juliemr** [comment]
website generation isn't tied to the version of Angular here, it gets it from the CDN. `npm test` is passing. I'll merge.

**Comment by juliemr** [comment]
merged as 6f7140aeead3715dd0dd365921fb886f58c6fbda

**Pull request closed without merging**
