### PR TITLE
fix: #5486 upgrade webdriver-manager to version 12.1.8

### PR DESCRIPTION
**Pull request by szgabsz91**
This upgrade fixes a problem in case of Intel based macos, where the
old webdriver-manager downloaded the m1 version of chromedriver. For
more details, see: https://github.com/angular/webdriver-manager/issues/476

### CODE REVIEW

**Comment by szgabsz91** [comment]
@googlebot I signed it!

**Review by kiruthikaponnusamy0503 — APPROVED** [review]

**Comment by szgabsz91** [comment]
@kiruthikaponnusamy0503 could you please help in what the problem might be with the CI jobs? It seems to me that these are environmental issues and not functional ones. Should I force push an amended commit to rerun the jobs, or it will fail again and I need to do something else?

**Review by StanislavKharchenko — APPROVED** [review]

**Review by StanislavKharchenko — APPROVED** [review]

**Comment by dennisporterjr** [comment]
Do we know what's going with this PR @szgabsz91? This is causing a lot of headaches for my colleagues and I with intel based macs...

**Comment by StanislavKharchenko** [comment]
It should be approved by repo owners. @kyliau @alan-agius4 please assist.

**Comment by szgabsz91** [comment]
@dennisporterjr There is also a workaround pointed out in the linked webdriver-manager issue that solved my problem even without merging this PR, maybe it helps you, too: `npm install --force protractor`

**Comment by Splaktar** [comment]
I think that it would be helpful to get this branch cleaned up. It should have 1 commit to fix this, not 19 extra, unrelated commits from `master`. Can you please reset the branch to the proper commit and rebase it on latest `master`?

I guess this is likely related to @kyliau's push a couple of weeks ago. It looks like that didn't quite fix things.

**Comment by StanislavKharchenko** [comment]
The master branch now reflect Protractor with new selenium and also webdriver-manager 13. However this PR related to webdriver-manager ver 12.x.

**Comment by szgabsz91** [comment]
Yeah, actually the version of webdriver-manager is higher than the one in this PR, so I just close this PR. Actually, as it turned out, force installing protractor also solved the original problem.

**Pull request closed without merging**
