### PR TITLE
chore(webdriver): upgrade Protractor to webdriver 2.48.2

### PR DESCRIPTION
**Pull request by hankduan**
Pending selenium-webdriver@2.48.2's release

### CODE REVIEW

**Comment by juliemr** [comment]
It's out now! I've kicked off the Travis tests again.

When updating the commit message, be sure to include the breaking changes and a link to https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md

**Comment by juliemr** [comment]
Oh, and we'll also have to kick node 0.10 and 0.12 off of the list of things we test in Travis.

**Comment by antoinebrault** [comment]
chromedriver 2.20 is out too.
https://chromedriver.storage.googleapis.com/index.html?path=2.20/

**Comment by juliemr** [comment]
Lgtm. We can do the chromedriver upgrade in another PR or this one, doesn't matter to me.

**Comment by hankduan** [comment]
Let's upgrade chromedriver in a later PR. I want to keep this PR just to the webdriver 2.48.x change.

**Comment by hankduan** [comment]
merged with https://github.com/angular/protractor/commit/18e1f71a4dd868709f4e259e05a8a196921e22be

**Pull request closed without merging**
