### PR TITLE
Upgrade to jasmine 3.1.0

### LINKED ISSUE #4788: Upgrade to jasmine 3.1.0
Feature Request
---

Upgrade to jasmine 3.1.0

Jasmine 3 has been released for a while. A particular reason I want protractor to follow up is   jasmine/jasmine/#842 finally allow specDone support async.

### PR DESCRIPTION
**Pull request by awarecan**
resolve #4788, #4708 

Jamine 3 change the random default to true, however I want to keep protractor's default to false to avoid breaking changes.
done() accept error as parameter in Jasmine 3
beforeEach() no longer allow in it() in Jasmine 3

### CODE REVIEW

**Comment by awarecan** [comment]
@qiyigg Could you help to review it again? I messed up previous PR.

To answer two of your code review concern in previous PR:

1. why remove this?
```expect(e.code).toBe(BrowserError.CODE);```

The purpose of this test is validate if error be thrown, not to verify the error code. I am not sure what is the root cause, but the exception don't have code property on my environment, the test will fail.

2. ```}, done());```
The "then" function receives a Function as parameter, passing done() to it will call "done" first and make the test always pass, won't it?

This test is expecting exception thrown, so if error occurred, done(), test passed.
One big change in Jasmine 3 is done() accept one parameter now, if we pass done function here, done(e) will be called, Jasmine will fail the test. 
I sightly changed the code in this PR

**Comment by awarecan** [comment]
Did I just ruined my PR again?

**Comment by qiyigg** [comment]
@awarecan I guess so... what you need to do is:
fetch the latest master branch
*rebase* your pr on that branch

**Comment by awarecan** [comment]
Recreate a new PR

**Pull request closed without merging**
