### PR TITLE
Protractor Tests using Docker

### PR DESCRIPTION
**Pull request by jags14385**
** ++ Documentation**

This adds documentation around how one can run tests using docker & Protractor.  Its a small tutorial/walkthrough around it.

### CODE REVIEW

**Comment by jags14385** [comment]
I signed it!

**Comment by jags14385** [comment]
I signed it!

**Comment by jags14385** [comment]
Updated the email ID

**Comment by jags14385** [comment]
@juliemr  Should I add this to the official cookbook repo & delete this pull request here ?

**Comment by mgiambalvo** [comment]
Thanks for doing this! I've been meaning to set up something similar. And yes, please make this a PR against the official cookbook instead.

**Comment by jags14385** [comment]
@mgiambalvo  : Created the PR in the protractor cookbook repo. :)

**Pull request closed without merging**
