### PR TITLE
tests(element): add a test that fails when finding subelements within ea...

### PR DESCRIPTION
**Pull request by juliemr**
...ch

[Review on Reviewable](https://reviewable.io/reviews/angular/protractor/2029)

### CODE REVIEW

**Comment by juliemr** [comment]
WIP - this does not yet fix the problem, just shows it.

**Comment by juliemr** [comment]
Should be fixed when #2245 is done.

**Comment by hankduan** [comment]
FYI: in your original example (from the PR), if you replace the protractor-defined locator i.e. `by.binding('username')` by a webdriver-native locator i.e. `by.css('#animals')`, then the example will hang for both selenium-webdriver 2.46.1 and lower versions.

**Comment by hankduan** [comment]
Reported reduced case here: https://github.com/SeleniumHQ/selenium/issues/715

**Comment by juliemr** [comment]
Updating this, now that we're using selenium-webdriver 2.47

**Comment by hankduan** [comment]
Is this still an issue with 2.48.2?

**Comment by juliemr** [comment]
Sorry for the delay - yes, this is working now. I'll submit to make sure we're testing for it in the future.

**Comment by juliemr** [comment]
Merged with 586d634bcd306a3226fd4c55bef43155294bad4e

**Pull request closed without merging**
