### PR TITLE
feature/shadow-root-locator

### PR DESCRIPTION
**Pull request by firstor**
Implemented new Protractor locator to select elements inside shadow-root.
For the background: https://github.com/angular/protractor/issues/4367

### CODE REVIEW

**Comment by nickiannone** [comment]
Could we please address the CI issues? I'm missing a LOT of test coverage because of inability to test shadow DOM elements.

**Comment by first87** [comment]
@nickiannone There seemed no error happened from `by.shadowRoot` side. I wrote a spec for `shadowRoot` locator and it passed the CircleCI test.

**Comment by whyboris** [comment]
Any update on this? Would be great to have <3

**Comment by first87** [comment]
I don't know why CircleCI build failed ~ I discard my changes and then tried again but it kept to fail.

**Comment by dweill** [comment]
Have you seen this @first87 
https://stackoverflow.com/questions/38176194/cannot-find-module-built-cli-js-when-running-protractor

**Comment by qiyigg** [comment]
To get circleCI work, you need rebase your PR to the latest version. Check(#4669)

**Comment by firstor** [comment]
Moved to new PR #4786

**Pull request closed without merging**
